name: "Auto PR: bugfix to develop"
on:
  push:
    branches:
      - 'bugfix/**'
jobs:
  auto-pr:
    name: bugfix to develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "fix: merge ${{ github.ref_name }} into develop"
          body: "Automated PR to merge bugfix branch into develop."
          delete-branch: false
